---
- hosts: webserver

  pre_tasks:
    - name: "Update cache"
      apt: update_cache=yes
    - name: "System upgrade"
      apt: upgrade=dist

  roles:
    - webserver
    - db
    - code
    - certificate
    - firewall

  vars:
    allowed_ports: ['http', 'https']
...
